### ISSUE TITLE
Issue on the render texture of the apiarist zombie villager entity on forge 31.2.0 (1.15.2)

### ISSUE THREAD

**Issue by solarblindfull** [team-abnormals/buzzier-bees#60]
Hi !
Thank you for this very good mod ! I'm on Forge 1.15.2 31.2.0 and unfortunately, I have an issue on the render of the apiarist zombie villager texture. Can you see what's wrong please ? You can see it in the Forge client log below. Thank you very much !

______________________________________________________________________________________________________

[Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: buzzierbees:textures/entity/zombie_villager/profession/apiarist.png
java.io.FileNotFoundException: buzzierbees:textures/entity/zombie_villager/profession/apiarist.png
	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:60) ~[?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:59) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.func_217799_a(SimpleTexture.java:113) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_215246_b(SimpleTexture.java:85) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_195413_a(SimpleTexture.java:38) ~[?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_230183_b_(TextureManager.java:122) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_229263_a_(TextureManager.java:100) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_229269_d_(TextureManager.java:83) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:63) [?:?]
	at net.minecraft.client.renderer.RenderState$TextureState.lambda$new$0(RenderState.java:690) [?:?]
	at net.minecraft.client.renderer.RenderState$TextureState$$Lambda$4633/1815684842.run(Unknown Source) [?:?]
	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) [?:?]
	at net.minecraft.client.renderer.RenderType$Type$$Lambda$12712/942241034.accept(Unknown Source) [?:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) [guava-21.0.jar:?]
	at net.minecraft.client.renderer.RenderType$Type.lambda$new$0(RenderType.java:819) [?:?]
	at net.minecraft.client.renderer.RenderType$Type$$Lambda$4689/78849157.run(Unknown Source) [?:?]
	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) [?:?]
	at net.minecraft.client.renderer.RenderType.func_228631_a_(RenderType.java:470) [?:?]
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.func_228462_a_(IRenderTypeBuffer.java:119) [?:?]
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.getBuffer(IRenderTypeBuffer.java:66) [?:?]
	at net.minecraft.client.renderer.entity.layers.LayerRenderer.func_229141_a_(SourceFile:31) [?:?]
	at net.minecraft.client.renderer.entity.layers.VillagerLevelPendantLayer.func_225628_a_(SourceFile:78) [?:?]
	at net.minecraft.client.renderer.entity.layers.VillagerLevelPendantLayer.func_225628_a_(SourceFile:30) [?:?]
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:228) [?:?]
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:47) [?:?]
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:20) [?:?]
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:300) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1854) [?:?]
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:386) [?:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4248) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:686) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/454992345.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]

**Comment by bageldotjpg** [comment]
Will be fixed next release as of 5aaf4135ab75843a05ce8b84bd0778d008eb6fb0
